# How to create CSV file

In [6]:
import pandas as pd
dic = {"a":[1,2,3,4], "b":[1,2,3,4]}

var = pd.DataFrame(dic)
var["sum"] = var["a"]+var["b"]
var

var.to_csv("sum_of_a&b.csv")
var.to_csv("sum_without_index.csv", index=False)
var.to_csv("header_change.csv", index = False, header = ["A", "B", "C"])
var

   a  b  sum
0  1  1    2
1  2  2    4
2  3  3    6
3  4  4    8

# How to Read CSV file

In [34]:
csv_1 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv")
csv_1

     SIC Code                                        Description
0        1110  Growing of cereals (except rice), leguminous c...
1        1120                                    Growing of rice
2        1130  Growing of vegetables and melons, roots and tu...
3        1140                              Growing of sugar cane
4        1150                                 Growing of tobacco
..        ...                                                ...
726     98000                      Residents property management
727     98100  Undifferentiated goods-producing activities of...
728     98200  Undifferentiated service-producing activities ...
729     99000  Activities of extraterritorial organizations a...
730     99999                                    Dormant Company

[731 rows x 2 columns]

### Printing a particular row

In [40]:
csv_2 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", nrows=2)
csv_2

   SIC Code                                        Description
0      1110  Growing of cereals (except rice), leguminous c...
1      1120                                    Growing of rice

In [42]:
csv_3 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", nrows=4)
csv_3

   SIC Code                                        Description
0      1110  Growing of cereals (except rice), leguminous c...
1      1120                                    Growing of rice
2      1130  Growing of vegetables and melons, roots and tu...
3      1140                              Growing of sugar cane

### Printing single column

In [47]:
csv_4 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", nrows =20, usecols=["SIC Code"])
csv_4

    SIC Code
0       1110
1       1120
2       1130
3       1140
4       1150
5       1160
6       1190
7       1210
8       1220
9       1230
10      1240
11      1250
12      1260
13      1270
14      1280
15      1290
16      1300
17      1410
18      1420
19      1430

### Skip a particular row

In [52]:
csv_5 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", skiprows = [0,1])
csv_5

      1120                                    Growing of rice
0     1130  Growing of vegetables and melons, roots and tu...
1     1140                              Growing of sugar cane
2     1150                                 Growing of tobacco
3     1160                             Growing of fibre crops
4     1190               Growing of other non-perennial crops
..     ...                                                ...
724  98000                      Residents property management
725  98100  Undifferentiated goods-producing activities of...
726  98200  Undifferentiated service-producing activities ...
727  99000  Activities of extraterritorial organizations a...
728  99999                                    Dormant Company

[729 rows x 2 columns]

### Index change

In [62]:
csv_6 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", index_col=[0])
csv_6 #Now sic code will work as index no.

                                                Description
SIC Code
1110      Growing of cereals (except rice), leguminous c...
1120                                        Growing of rice
1130      Growing of vegetables and melons, roots and tu...
1140                                  Growing of sugar cane
1150                                     Growing of tobacco
...                                                     ...
98000                         Residents property management
98100     Undifferentiated goods-producing activities of...
98200     Undifferentiated service-producing activities ...
99000     Activities of extraterritorial organizations a...
99999                                       Dormant Company

[731 rows x 1 columns]

### Header change

In [67]:
csv_7 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", header=2)
csv_7 # It means, row no.2 will work as header

      1120                                    Growing of rice
0     1130  Growing of vegetables and melons, roots and tu...
1     1140                              Growing of sugar cane
2     1150                                 Growing of tobacco
3     1160                             Growing of fibre crops
4     1190               Growing of other non-perennial crops
..     ...                                                ...
724  98000                      Residents property management
725  98100  Undifferentiated goods-producing activities of...
726  98200  Undifferentiated service-producing activities ...
727  99000  Activities of extraterritorial organizations a...
728  99999                                    Dormant Company

[729 rows x 2 columns]

### Change names of header

In [76]:
csv_8 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", names = ["code","details"])
csv_8

         code                                            details
0    SIC Code                                        Description
1        1110  Growing of cereals (except rice), leguminous c...
2        1120                                    Growing of rice
3        1130  Growing of vegetables and melons, roots and tu...
4        1140                              Growing of sugar cane
..        ...                                                ...
727     98000                      Residents property management
728     98100  Undifferentiated goods-producing activities of...
729     98200  Undifferentiated service-producing activities ...
730     99000  Activities of extraterritorial organizations a...
731     99999                                    Dormant Company

[732 rows x 2 columns]

### How to delete header

In [87]:
csv_9 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", header = None)
csv_9

            0                                                  1
0    SIC Code                                        Description
1        1110  Growing of cereals (except rice), leguminous c...
2        1120                                    Growing of rice
3        1130  Growing of vegetables and melons, roots and tu...
4        1140                              Growing of sugar cane
..        ...                                                ...
727     98000                      Residents property management
728     98100  Undifferentiated goods-producing activities of...
729     98200  Undifferentiated service-producing activities ...
730     99000  Activities of extraterritorial organizations a...
731     99999                                    Dormant Company

[732 rows x 2 columns]

### Convert Datatype of particular columns

In [92]:
csv_10 = pd.read_csv("C:\\Users\\KIIT\\Pandas\\industry_sic.csv", dtype={"SIC Code": "float"})
csv_10

     SIC Code                                        Description
0      1110.0  Growing of cereals (except rice), leguminous c...
1      1120.0                                    Growing of rice
2      1130.0  Growing of vegetables and melons, roots and tu...
3      1140.0                              Growing of sugar cane
4      1150.0                                 Growing of tobacco
..        ...                                                ...
726   98000.0                      Residents property management
727   98100.0  Undifferentiated goods-producing activities of...
728   98200.0  Undifferentiated service-producing activities ...
729   99000.0  Activities of extraterritorial organizations a...
730   99999.0                                    Dormant Company

[731 rows x 2 columns]