# Dataframe

In [15]:
import pandas as pd
l = [1,2,3,4,5,6]
var = pd.DataFrame(l)
print(type(var))
print()
var

<class 'pandas.core.frame.DataFrame'>

   0
0  1
1  2
2  3
3  4
4  5
5  6

## Dictionary

In [36]:
dec = {"age":[20,22,23,26,19],"marks":[85,45,98,44,67]}
var1 = pd.DataFrame(dec)
var1

   age  marks
0   20     85
1   22     45
2   23     98
3   26     44
4   19     67

In [42]:
dec2 = {"age":[20,22,23,26],"marks":[85,45,98,44], 1:[1,2,3,4], "a":['a','s','d','f']}
var2 = pd.DataFrame(dec2, columns =["a",1,"age"], index=[1,2,3,4])
print()
var2

   a  1  age
1  a  1   20
2  s  2   22
3  d  3   23
4  f  4   26

## How to get data?

In [55]:
dec3 = {"age":[20,22,23,26],"marks":[85,45,98,44], 1:[1,2,3,4], "a":['a','s','d','f']}
var3 = pd.DataFrame(dec2)
print(var3)
print()

print(var3["marks"][2])

   age  marks  1  a
0   20     85  1  a
1   22     45  2  s
2   23     98  3  d
3   26     44  4  f

98

## Using list

In [60]:
list = ([[1,2,3,4],[9,8,7,6]])
l = pd.DataFrame(list)
l

   0  1  2  3
0  1  2  3  4
1  9  8  7  6

## Using series

In [63]:
serv = {"s":pd.Series([1,2,3,4]), "p":pd.Series([9,3,45,5])}
d = pd.DataFrame(serv)
d

   s   p
0  1   9
1  2   3
2  3  45
3  4   5